### ISSUE TITLE
ARM64

### ISSUE THREAD

**Issue by OneOfTheMicahs** [YunoHost-Apps/silverbullet_ynh#5]
Can you add arm64 as a possible architecture? I'd like to install on my raspeberry pi, but it is restricted to amd64 right now.

From what I can tell, architecture restrictions for Silverbullet come directly from the architectures that the Deno runtime can run on. There are slightly different installation instructions to install Deno on arm64, but otherwise, Silverbullet works as expected: https://github.com/silverbulletmd/silverbullet/issues/136.

**Comment by fflorent** [comment]
Deploying for arm64 is hard as only amd64 binary is provided. It would make the installation and the deployment harder to build the project using deno.

Probably worth to take a look at the upstream project and see how hard building for arm64 would be.

**Comment by fflorent** [comment]
Created this PR:
https://github.com/silverbulletmd/silverbullet/pull/906

**Comment by fflorent** [comment]
ARM64 is supported. I tested on a VPS, it worked on my side..

Feedback welcome :)

**Comment by Panz00** [comment]
Works well for me on a Raspberry Pi 3.

Thanks a lot !
